### ISSUE TITLE
[Question]How do we access the secrets mounted in the /tmp/secret to k8s-env ?

### ISSUE THREAD

**Issue by santhoshtricon** [aws-samples/aws-secret-sidecar-injector#18]
Hi ,

Am not able to locate to the fetch the environment variable which is mounted in the /tmp/secret path .

/tmp/secret wil contain the key/value pair .
eg :
{"username":"admin","password":"P@$$word1024","engine":"mysql","host":"database-1.cluster.us-east-1.rds.amazonaws.com","port":3306,"dbClusterIdentifier":"database-1"}

But I want to pass the these value to the kubernets environment 

something like this : 
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: DATABASE_URL
or         env:
        - name: DATABASE_URL
          value: /tmp/secret
..
As /tmp/secret file contains the key value pair in it . Am unable to fetch to the k8s-envi file.

If you know any possible cases please do let me know...

**Comment by jicowan** [comment]
@santhoshtricon You have to read the file and parse it.  This is similar to the behavior of Kubernetes Secrets when you mount them as volumes.  I prefer this approach because the value of environment variables can leak.  If you rather map a secret to an environment variable, I suggest using GoDaddy's [External Secrets](https://www.godaddy.com/engineering/2019/04/16/kubernetes-external-secrets/) project. Unlike this project, External Secrets will synchronize secrets in AWS Secrets Manager with k8s Secrets. You simply need to reference the k8s Secret when you want to use it.

**Comment by santhoshtricon** [comment]
Thank you @jicowan
