### ISSUE TITLE
Production readiness

### ISSUE THREAD

**Issue by pbn4** [aws-samples/aws-secret-sidecar-injector#34]
Hello,

> Lastly, the purpose of this Poc is to demonstrate the type of integration that can be achieved between AWS Secrets Manager and Kubernetes. It is not meant to be used in production.

why is this sample not meant to be used in production?

[AWS Secrets Controller PoC: integrating AWS Secrets Manager with Kubernetes](https://aws.amazon.com/blogs/containers/aws-secrets-controller-poc/)

**Comment by jicowan** [comment]
@pbn4 This was really meant be to a reference implementation.  The reason it is not for production use is because a) it is not directly supported by AWS b) it has not been tested at scale and c) there's no SLA for fixing bugs.  Of course you _can_  use it in production, but you would do so at your own risk.  While we think the overall risk is minimal, we don't want to blamed for causing a production outage, e.g. if an application can't retrieve a secret for a system in the critical path. I hope that makes sense.
